function test() {
    try {
        let a = 0;
    } catch (err) {
        let b = 1;
    }
    let c = 2;
    let d = 3;
}